name: Python Tests and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Linting with flake8
      run: |
        source env/bin/activate
        flake8 app/ tests/

    - name: Run isort (Check Only)
      run: |
        source env/bin/activate
        isort --check-only app/ tests/

    - name: Run Black (Check Only)
      run: |
        source env/bin/activate
        black --check app/ tests/

    - name: Run Tests
      run: |
        source env/bin/activate
        pytest --cov=app